### ISSUE TITLE
[USERSTORY] Setup formatting

### ISSUE THREAD

**Issue by LC117** [Generation-D/application-platform#50]
1. As a developer
1. I want/need consistently formatted python code
1. So that I can work faster with formatted code, and it's easier for others to work with it

### Acceptance Criteria

- Updated README
- Added GitHub action automatically checking for consistency when a push is made. 

### Dependency

The following Issues must be done first:
-

**Comment by Interperle** [comment]
@LC117 kannst du bitte für Issues unserer Issue Template verwenden? Bitte dieses hier dann noch nachträglich einbetten

**Comment by Interperle** [comment]
closed by #62
